# Generated by Django 4.1.4 on 2023-03-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('schools', '0002_alter_schoolregister_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.grades')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolregister')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
