# Generated by Django 4.1.4 on 2023-03-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schoolregister',
            table='schoolregister',
        ),
    ]
