# Generated by Django 4.1.4 on 2023-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_schoolregister_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolregister',
            name='access',
            field=models.TextField(default='acs'),
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='refresh',
            field=models.TextField(default='ref'),
        ),
    ]
